"""auto update

Revision ID: 04d8dd34e749
Revises: a6982516d512
Create Date: 2026-07-06 11:42:08.562231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d8dd34e749'
down_revision: Union[str, Sequence[str], None] = 'a6982516d512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('lot_variant_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_logs', 'lot_variant_name')
    # ### end Alembic commands ###