"""auto update

Revision ID: 123cf0a90b18
Revises: b0c3f2b05899
Create Date: 2026-08-12 08:46:20.768334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123cf0a90b18'
down_revision: Union[str, Sequence[str], None] = 'b0c3f2b05899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot_configs', 'lot_name')
    op.drop_column('lot_configs', 'location')
    op.drop_column('lot_configs', 'is_custom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot_configs', sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lot_configs', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lot_configs', sa.Column('lot_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###