"""auto update

Revision ID: 15d9c04effc6
Revises: 123cf0a90b18
Create Date: 2026-08-13 06:41:53.558294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d9c04effc6'
down_revision: Union[str, Sequence[str], None] = '123cf0a90b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('intervention_type', sa.String(), nullable=True))
    op.alter_column('inventory_logs', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_logs', 'lot_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_logs', 'sub_entity_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_logs', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_logs', 'completed_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('inventory_sessions', sa.Column('intervention_type', sa.String(), nullable=True))
    op.alter_column('inventory_sessions', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_sessions', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_sessions', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_sessions', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('inventory_sessions', 'intervention_type')
    op.alter_column('inventory_logs', 'completed_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_logs', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_logs', 'sub_entity_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_logs', 'lot_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_logs', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('inventory_logs', 'intervention_type')
    # ### end Alembic commands ###