"""auto update

Revision ID: 852b2ced5bf9
Revises: 04d8dd34e749
Create Date: 2026-07-06 11:52:29.037480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852b2ced5bf9'
down_revision: Union[str, Sequence[str], None] = '04d8dd34e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discrepancy_reports', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discrepancy_reports', 'dps_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###