"""auto update

Revision ID: a19da0451f6a
Revises: 8af34ea243a5
Create Date: 2026-07-06 08:57:04.967656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19da0451f6a'
down_revision: Union[str, Sequence[str], None] = '8af34ea243a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('lot_name', sa.String(), nullable=False),
    sa.Column('sub_entity_name', sa.String(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=True),
    sa.Column('sac_type', sa.String(), nullable=True),
    sa.Column('dps_name', sa.String(), nullable=False),
    sa.Column('completed_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    # ### end Alembic commands ###