"""auto update

Revision ID: a6982516d512
Revises: a19da0451f6a
Create Date: 2026-07-06 09:16:44.123634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6982516d512'
down_revision: Union[str, Sequence[str], None] = 'a19da0451f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrepancy_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('report_key', sa.String(), nullable=False),
    sa.Column('lot_name', sa.String(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=True),
    sa.Column('dps_name', sa.String(), nullable=False),
    sa.Column('discrepancies_json', sa.String(), nullable=True),
    sa.Column('full_inventory_json', sa.String(), nullable=True),
    sa.Column('has_discrepancies', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancy_reports_id'), 'discrepancy_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discrepancy_reports_id'), table_name='discrepancy_reports')
    op.drop_table('discrepancy_reports')
    # ### end Alembic commands ###