"""auto update

Revision ID: aa11a86d9555
Revises: e1745981cf1c
Create Date: 2026-08-10 08:07:34.680099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa11a86d9555'
down_revision: Union[str, Sequence[str], None] = 'e1745981cf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_discrepancy_reports_lot_id'), 'discrepancy_reports', ['lot_id'], unique=False)
    op.create_index(op.f('ix_discrepancy_reports_variant_id'), 'discrepancy_reports', ['variant_id'], unique=False)
    op.alter_column('inventory_items', 'validated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_items_item_id'), 'inventory_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_session_id'), 'inventory_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_sub_entity_id'), 'inventory_items', ['sub_entity_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_variant_id'), 'inventory_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_inventory_logs_lot_id'), 'inventory_logs', ['lot_id'], unique=False)
    op.alter_column('inventory_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_sessions_lot_id'), 'inventory_sessions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_inventory_sessions_variant_id'), 'inventory_sessions', ['variant_id'], unique=False)
    op.alter_column('lot_configs', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_sub_entity_checks_session_id'), 'sub_entity_checks', ['session_id'], unique=False)
    op.create_index(op.f('ix_sub_entity_checks_sub_entity_id'), 'sub_entity_checks', ['sub_entity_id'], unique=False)
    op.create_index(op.f('ix_sub_entity_checks_variant_id'), 'sub_entity_checks', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_entity_checks_variant_id'), table_name='sub_entity_checks')
    op.drop_index(op.f('ix_sub_entity_checks_sub_entity_id'), table_name='sub_entity_checks')
    op.drop_index(op.f('ix_sub_entity_checks_session_id'), table_name='sub_entity_checks')
    op.alter_column('lot_configs', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_sessions_variant_id'), table_name='inventory_sessions')
    op.drop_index(op.f('ix_inventory_sessions_lot_id'), table_name='inventory_sessions')
    op.alter_column('inventory_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_logs_lot_id'), table_name='inventory_logs')
    op.drop_index(op.f('ix_inventory_items_variant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sub_entity_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_session_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_id'), table_name='inventory_items')
    op.alter_column('inventory_items', 'validated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_index(op.f('ix_discrepancy_reports_variant_id'), table_name='discrepancy_reports')
    op.drop_index(op.f('ix_discrepancy_reports_lot_id'), table_name='discrepancy_reports')
    # ### end Alembic commands ###