"""auto update

Revision ID: e1745981cf1c
Revises: 5fdc21dfc201
Create Date: 2026-08-10 04:59:28.800565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1745981cf1c'
down_revision: Union[str, Sequence[str], None] = '5fdc21dfc201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('lot_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_configs_id'), 'lot_configs', ['id'], unique=False)
    op.create_index(op.f('ix_lot_configs_lot_id'), 'lot_configs', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_configs_lot_id'), table_name='lot_configs')
    op.drop_index(op.f('ix_lot_configs_id'), table_name='lot_configs')
    op.drop_table('lot_configs')
    # ### end Alembic commands ###